// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhKZcSEWk9p_L1c5DZDOknWusf7nZc9yU',
    appId: '1:551683394424:web:8db7e946b7547ebf59568d',
    messagingSenderId: '551683394424',
    projectId: 'bayutapp-c93eb',
    authDomain: 'bayutapp-c93eb.firebaseapp.com',
    storageBucket: 'bayutapp-c93eb.appspot.com',
    measurementId: 'G-QENKDMMEY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZusSLPA1q8o8moRpV8UKEVsdiHRf9AXg',
    appId: '1:551683394424:android:d88ce23cd45afa0359568d',
    messagingSenderId: '551683394424',
    projectId: 'bayutapp-c93eb',
    storageBucket: 'bayutapp-c93eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrslxb0m0oOtnzJE8kR8ZQlp2z8g9Wz80',
    appId: '1:551683394424:ios:537a6a6316bf37d359568d',
    messagingSenderId: '551683394424',
    projectId: 'bayutapp-c93eb',
    storageBucket: 'bayutapp-c93eb.appspot.com',
    iosBundleId: 'com.example.bayutCloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrslxb0m0oOtnzJE8kR8ZQlp2z8g9Wz80',
    appId: '1:551683394424:ios:537a6a6316bf37d359568d',
    messagingSenderId: '551683394424',
    projectId: 'bayutapp-c93eb',
    storageBucket: 'bayutapp-c93eb.appspot.com',
    iosBundleId: 'com.example.bayutCloneApp',
  );
}
